# I. Collecting dataset

Bây giờ ta sẽ nhập các dữ liệu đang có thành 1 DataFrame mới

In [1]:
import pandas as pd

Load nội dung `company_name.txt`

In [2]:
comapanies_names = pd.read_csv('../Data/company_name.txt', header=None)
comapanies_names.tail()

                               0
1995  taishin-financial-holdings
1996                        saab
1997                     carvana
1998                         kbr
1999                     vf-corp

Load nội dung `companies.csv`

In [3]:
companies_df = pd.read_csv('../Data/companies.csv')
companies_df.tail()

,Name,Marketcap,Country,Share price,Change (1 day),Change (1 year),Categories
1995,Taishin Financial Holdings,$7.10 B,Taiwan,$0.57,-0.56%,18.75%,"🏦 Banks, 💳 Financial services"
1996,SAAB AB,$7.04 B,Sweden,$52.39,1.87%,34.96%,"🚀 Aerospace, 🔫 Defense contractors"
1997,Carvana,$7.15 B,USA,$40.26,6.23%,711.69%,"🛒 E-Commerce, 🖥️ Internet, 🚘 Used car retailer..."
1998,KBR,$7.05 B,USA,$52.24,-0.59%,1.56%,👷 Engineering
1999,VF Corporation,$7.05 B,USA,$18.14,0.17%,-36.73%,"👚 Clothing, 👟 Footwear"

Ta nhận thấy không cần các cột:

- `Marketcap`
- `Share price`
- `Change (1 day)`
- `Change (1 year)`

Do đó ta sẽ drop các cột này

In [4]:
companies_df.drop(columns=['Marketcap','Change (1 day)','Change (1 year)'], inplace=True)
companies_df

,Name,Country,Share price,Categories
0,Apple,USA,$195.71,"👨‍💻 Software, 👩‍💻 Tech, 🔌 Electronics, 🇺🇸 Dow ..."
1,Microsoft,USA,$374.23,"👨‍💻 Software, 👩‍💻 Tech, 🎮 Video games, 🇺🇸 Dow ..."
2,Saudi Aramco,Saudi Arabia,$8.82,"🛢 Oil&Gas, ⚡ Energy"
3,Alphabet (Google),USA,$136.64,"👨‍💻 Software, 🖥️ Internet, 👩‍💻 Tech, 🤖 Autonom..."
4,Amazon,USA,$147.42,"🛒 E-Commerce, 🛍️ Retail, 🖥️ Internet, 👩‍💻 Tech"
...,...,...,...,...
1995,Taishin Financial Holdings,Taiwan,$0.57,"🏦 Banks, 💳 Financial services"
1996,SAAB AB,Sweden,$52.39,"🚀 Aerospace, 🔫 Defense contractors"
1997,Carvana,USA,$40.26,"🛒 E-Commerce, 🖥️ Internet, 🚘 Used car retailer..."
1998,KBR,USA,$52.24,👷 Engineering
1999,VF Corporation,USA,$18.14,"👚 Clothing, 👟 Footwear"

Bây giờ, ta sẽ đọc lên các data đã thu thập được

In [5]:
revenue_df = pd.read_csv('../Data/revenue.csv')
marketcap_df = pd.read_csv('../Data/marketcap.csv')
earnings_df = pd.read_csv('../Data/earnings.csv')
eps_df = pd.read_csv('../Data/eps.csv')
debts_df = pd.read_csv('../Data/debts.csv')
net_assets_df = pd.read_csv('../Data/net_assets.csv')
total_assets_df = pd.read_csv('../Data/total_assets.csv')
cash_on_hand_df = pd.read_csv('../Data/cash_on_hand.csv')

In [6]:
revenue_df.tail()

,Company,2023 (TTM),2022,2021,2020,2019,2018,2017,2016,2015,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
1995,taishin-financial-holdings,$2.32 B,$2.20 B,$2.08 B,$1.45 B,$1.31 B,$1.20 B,$1.12 B,$0.99 B,$1.02 B,...,$1.34 B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,saab,$4.64 B,$4.11 B,$4.46 B,$3.95 B,$3.76 B,$3.76 B,$3.73 B,$3.33 B,$3.23 B,...,$3.45 B,$3.31 B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,carvana,$11.18 B,$13.60 B,$12.81 B,$5.58 B,$3.93 B,$1.95 B,$0.85 B,$0.36 B,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,kbr,$6.83 B,$6.56 B,$7.33 B,$5.76 B,$5.63 B,$4.91 B,$4.17 B,$4.26 B,$5.09 B,...,$10.07 B,$12.10 B,$11.58 B,$8.96 B,$9.63 B,$10.20 B,$11.96 B,NaN,NaN,NaN
1999,vf-corp,$11.39 B,$11.69 B,$11.59 B,$8.75 B,$12.26 B,$13.68 B,$12.09 B,$12.09 B,$12.37 B,...,$7.70 B,$7.22 B,$7.64 B,$7.21 B,$6.21 B,$6.42 B,$6.05 B,$5.20 B,$5.17 B,$5.51 B

In [7]:
marketcap_df.tail()

,Company,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
1995,taishin-financial-holdings,$7.10 B,$5.87 B,$7.81 B,$5.14 B,$5.13 B,$4.45 B,$4.63 B,$3.47 B,$3.15 B,...,$3.51 B,$2.09 B,$0.93 B,$2.36 B,$3.00 B,$2.77 B,NaN,NaN,NaN,NaN
1996,saab,$7.04 B,$5.18 B,$3.25 B,$3.76 B,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,carvana,$7.15 B,$0.84 B,$19.83 B,$41.14 B,$13.96 B,$4.76 B,$2.53 B,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,kbr,$7.05 B,$7.24 B,$6.68 B,$4.40 B,$4.32 B,$2.13 B,$2.77 B,$2.38 B,$2.40 B,...,$4.60 B,$3.04 B,$2.45 B,$6.58 B,$4.38 B,NaN,NaN,NaN,NaN,NaN
1999,vf-corp,$7.05 B,$10.72 B,$28.75 B,$33.31 B,$39.31 B,$28.21 B,$29.24 B,$22.07 B,$26.53 B,...,$9.34 B,$8.07 B,$6.02 B,$7.53 B,$9.20 B,$6.09 B,$6.16 B,$4.67 B,$3.91 B,$4.29 B

In [8]:
earnings_df.tail()

,Company,2023 (TTM),2022,2021,2020,2019,2018,2017,2016,2015,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
1995,taishin-financial-holdings,$0.69 B,$0.58 B,$0.82 B,$0.56 B,$0.52 B,$0.47 B,$0.49 B,$0.40 B,$0.46 B,...,$0.64 B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,saab,$0.39 B,$0.27 B,$0.29 B,$0.12 B,$0.27 B,$0.20 B,$0.23 B,$0.18 B,$0.20 B,...,$0.11 B,$0.13 B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,carvana,-$0.45 B,-$2.41 B,-$0.11 B,-$0.34 B,-$0.29 B,-$0.23 B,-$0.16 B,-$89.53 M,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,kbr,$3 M,$0.37 B,$0.22 B,$58 M,$0.36 B,$0.46 B,$0.26 B,-$31 M,$0.17 B,...,$0.61 B,$3.44 B,$0.54 B,$0.31 B,$0.24 B,-$0.36 B,NaN,NaN,NaN,NaN
1999,vf-corp,$0.48 B,$0.43 B,$1.44 B,-$22.27 M,$1.40 B,$1.64 B,$1.33 B,$1.41 B,$1.58 B,...,$0.75 B,$0.65 B,$0.84 B,$0.90 B,$0.77 B,$0.77 B,$0.71 B,$0.59 B,$0.56 B,$0.26 B

In [9]:
eps_df.tail()

,Company,2023 (TTM),2022,2021,2020,2019,2018,2017,2016,2015,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
1995,taishin-financial-holdings,$0.04481,$0.03403,$0.05321,$0.03506,$0.03282,$0.03039,$0.03038,$0.02776,$0.03140,...,$0.01733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,saab,$2.33,$1.62,$1.66,$0.90,$1.59,$1.27,$1.52,$1.13,$1.42,...,$0.53,$0.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,carvana,-$12.34,-$15.52,-$1.59,-$2.78,-$2.42,-$2.18,-$3.58,-$6.34,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998,kbr,-$1.44,$1.39,$0.19,-$0.52,$1.42,$1.98,$3.06,-$0.43,$1.40,...,$2.08,$1.81,$1.91,$1.80,$1.20,$1.76,-$2.23,NaN,NaN,NaN
1999,vf-corp,-$0.55,$1.07,$3.57,-$0.42,$3.25,$3.50,$1.55,$2.50,$2.89,...,$1.32,$1.05,$1.38,$1.34,$1.20,$1.14,$1.08,$0.91,-$0.19,$0.30

In [10]:
debts_df.tail()

,Company,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
1964,taishin-financial-holdings,NaN,$3.22 B,$3.92 B,$3.55 B,$3.11 B,$2.79 B,$3.03 B,$2.80 B,$2.72 B,...,$3.16 B,$2.77 B,$5.27 B,$6.27 B,$6.31 B,NaN,NaN,NaN,NaN,NaN
1965,saab,NaN,$0.96 B,$1.07 B,$1.22 B,$1.11 B,$1.03 B,$0.77 B,$0.65 B,$0.68 B,...,$0.25 B,$0.51 B,$0.49 B,NaN,NaN,NaN,NaN,$0.39 B,$0.39 B,NaN
1966,carvana,NaN,$8.81 B,$5.77 B,$1.87 B,$1.61 B,$0.63 B,$0.30 B,$0.17 B,$42.3 M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1967,kbr,NaN,$1.98 B,$2.08 B,$1.82 B,$1.43 B,$1.27 B,$0.50 B,$0.69 B,$61 M,...,NaN,NaN,NaN,NaN,$20 M,$0.80 B,$60 M,NaN,NaN,NaN
1968,vf-corp,$7.81 B,$6.44 B,$6.95 B,$4.85 B,$2.78 B,$3.74 B,$2.92 B,$2.31 B,$1.86 B,...,$0.97 B,$1.18 B,$1.19 B,$1.28 B,$0.79 B,$0.82 B,$1.00 B,$0.99 B,$0.66 B,$0.98 B

In [11]:
net_assets_df.tail()

,Company,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
1973,taishin-financial-holdings,NaN,$6.62 B,$7.16 B,$6.63 B,$5.95 B,$5.71 B,$5.23 B,$4.58 B,$3.90 B,...,$5.73 B,$4.89 B,$4.48 B,$4.84 B,$4.69 B,NaN,NaN,NaN,NaN,NaN
1974,saab,NaN,$2.87 B,$2.56 B,$2.64 B,$2.22 B,$2.18 B,$1.75 B,$1.46 B,$1.53 B,...,$1.69 B,$1.52 B,$1.19 B,$1.70 B,$1.43 B,$1.15 B,$1.22 B,$0.99 B,$0.79 B,NaN
1975,carvana,NaN,$-1.06 B,$0.52 B,$0.80 B,$0.19 B,$0.22 B,$0.27 B,$0.13 B,$65.2 M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1976,kbr,NaN,$1.63 B,$1.70 B,$1.60 B,$1.85 B,$1.73 B,$1.22 B,$0.74 B,$1.05 B,...,$2.20 B,$2.29 B,$2.03 B,$2.23 B,$1.82 B,$1.39 B,$0.92 B,NaN,$1.13 B,NaN
1977,vf-corp,$2.91 B,$3.53 B,$3.05 B,$3.35 B,$4.29 B,$3.68 B,$3.71 B,$4.94 B,$5.38 B,...,$3.86 B,$3.82 B,$3.55 B,$3.57 B,$3.26 B,$2.80 B,$2.51 B,$1.95 B,$1.65 B,$2.11 B

In [12]:
total_assets_df.tail()

,Company,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
1973,taishin-financial-holdings,NaN,$90.21 B,$90.84 B,$78.23 B,$67.53 B,$58.48 B,$56.57 B,$48.61 B,$47.52 B,...,$85.02 B,$74.32 B,$71.61 B,$72.12 B,$71.54 B,NaN,NaN,NaN,NaN,NaN
1974,saab,NaN,$6.95 B,$7.18 B,$7.39 B,$6.40 B,$6.25 B,$5.46 B,$4.53 B,$4.17 B,...,$4.33 B,$4.29 B,$4.20 B,$5.23 B,$4.79 B,$3.84 B,$4.14 B,$3.98 B,$3.23 B,NaN
1975,carvana,NaN,$8.69 B,$7.01 B,$3.03 B,$2.05 B,$0.99 B,$0.64 B,$0.33 B,$0.13 B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1976,kbr,NaN,$5.56 B,$6.19 B,$5.70 B,$5.36 B,$5.07 B,$3.67 B,$4.14 B,$3.41 B,...,$5.41 B,$5.32 B,$5.88 B,$5.20 B,$5.40 B,$5.18 B,$5.48 B,NaN,$4.03 B,NaN
1977,vf-corp,$13.99 B,$13.34 B,$13.75 B,$11.13 B,$10.35 B,$10.31 B,$9.95 B,$9.73 B,$9.63 B,...,$6.45 B,$6.48 B,$6.43 B,$6.44 B,$5.46 B,$5.17 B,$5.00 B,$4.24 B,$3.50 B,$4.10 B

In [13]:
cash_on_hand_df.tail()

,Company,2023,2022,2021,2020,2019,2018,2017,2016,2015,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
1965,taishin-financial-holdings,NaN,NaN,$4.13 B,$3.86 B,$3.04 B,$2.56 B,$2.65 B,$2.99 B,$2.15 B,...,$6.05 B,$8.42 B,$7.84 B,$8.78 B,$8.21 B,NaN,NaN,NaN,NaN,NaN
1966,saab,NaN,$1.23 B,$1.30 B,$1.26 B,$0.80 B,$1.27 B,$0.81 B,$0.65 B,$0.45 B,...,$0.60 B,$0.28 B,$0.10 B,$0.13 B,$0.20 B,$0.19 B,$0.17 B,$60.82 M,$56.14 M,NaN
1967,carvana,NaN,$0.43 B,$0.40 B,$0.30 B,$76.01 M,$78.86 M,$0.17 B,$39.18 M,$43.13 M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1968,kbr,NaN,$0.38 B,$0.37 B,$0.43 B,$0.71 B,$0.73 B,$0.43 B,$0.53 B,$0.88 B,...,$0.78 B,$0.94 B,$1.14 B,$1.86 B,$1.46 B,$0.39 B,$0.23 B,NaN,$0.85 B,NaN
1969,vf-corp,$0.81 B,$1.27 B,$1.41 B,$1.36 B,$0.54 B,$0.68 B,$0.56 B,$1.22 B,$0.94 B,...,$0.79 B,$0.73 B,$0.38 B,$0.32 B,$0.34 B,$0.29 B,$0.48 B,$0.51 B,$0.49 B,$0.33 B

Ta thấy rằng:

- Các tên công ti trong cột `Company` không trùng với tên công ty trong cột `Name` trong `companies_df`.  

- Giá trị `2023 (TTM)` được ghi thay vì  `2023` trong `eps_df`, `earings_df`, `revenue_df`

In [14]:
# Thay lại tên các công ty
# Đầu tiên ta tạo một dictionary với key là giá trị tên cần thay và value là tên sẽ thay
companies_dict = dict(zip(comapanies_names[0].tolist(), companies_df['Name'].tolist()))
companies_dict

{'apple': 'Apple',
 'microsoft': 'Microsoft',
 'saudi-aramco': 'Saudi Aramco',
 'alphabet-google': 'Alphabet (Google)',
 'amazon': 'Amazon',
 'nvidia': 'NVIDIA',
 'meta-platforms': 'Meta Platforms (Facebook)',
 'berkshire-hathaway': 'Berkshire Hathaway',
 'tesla': 'Tesla',
 'eli-lilly': 'Eli Lilly',
 'visa': 'Visa',
 'tsmc': 'TSMC',
 'united-health': 'UnitedHealth',
 'jp-morgan-chase': 'JPMorgan Chase',
 'novo-nordisk': 'Novo Nordisk',
 'walmart': 'Walmart',
 'lvmh': 'LVMH',
 'exxon-mobil': 'Exxon Mobil',
 'mastercard': 'Mastercard',
 'broadcom': 'Broadcom',
 'johnson-and-johnson': 'Johnson & Johnson',
 'tencent': 'Tencent',
 'samsung': 'Samsung',
 'procter-and-gamble': 'Procter & Gamble',
 'home-depot': 'Home Depot',
 'oracle': 'Oracle',
 'nestle': 'Nestlé',
 'kweichow-moutai': 'Kweichow Moutai',
 'asml': 'ASML',
 'adobe': 'Adobe',
 'chevron': 'Chevron',
 'costco': 'Costco',
 'abbvie': 'AbbVie',
 'merck': 'Merck',
 'l-oreal': "L'Oréal",
 'coca-cola': 'Coca-Cola',
 'toyota': 'Toyota',
 'bank-of-america': 'Bank of America',
 'salesforce': 'Salesforce',
 'international-holding-company': 'International Holding Company',
 'roche': 'Roche',
 'pepsico': 'Pepsico',
 'hermes-international': 'Hermès',
 'icbc': 'ICBC',
 'accenture': 'Accenture',
 'shell': 'Shell',
 'mcdonald': 'McDonald',
 'amd': 'AMD',
 'reliance-industries': 'Reliance Industries',
 'novartis': 'Novartis',
 'netflix': 'Netflix',
 'astrazeneca': 'AstraZeneca',
 'cisco': 'Cisco',
 'linde': 'Linde',
 'thermo-fisher-scientific': 'Thermo Fisher Scientific',
 'sap': 'SAP',
 'alibaba': 'Alibaba',
 'pinduoduo': 'Pinduoduo',
 'abbott-laboratories': 'Abbott Laboratories',
 't-mobile-us': 'T-Mobile US',
 'intel': 'Intel',
 'nike': 'Nike',
 'china-mobile': 'China Mobile',
 'agricultural-bank-of-china': 'Agricultural Bank of China',
 'walt-disney': 'Walt Disney',
 'petro-china': 'PetroChina',
 'comcast': 'Comcast',
 'wells-fargo': 'Wells Fargo',
 'pfizer': 'Pfizer',
 'danaher': 'Danaher',
 'hdfc-bank': 'HDFC Bank',
 'verizon': 'Verizon',
 'tata-consultancy-services': 'Tata Consultancy Services',
 'intuit': 'Intuit',
 'bhp-group': 'BHP Group',
 'totalenergies': 'TotalEnergies',
 'hsbc': 'HSBC',
 'qualcomm': 'QUALCOMM',
 'ibm': 'IBM',
 'china-construction-bank': 'China Construction Bank',
 'bank-of-china': 'Bank of China',
 'boeing': 'Boeing',
 'amgen': 'Amgen',
 'servicenow': 'ServiceNow',
 'texas-instruments': 'Texas Instruments',
 'prosus': 'Prosus',
 'philip-morris': 'Philip Morris',
 'union-pacific-corporation': 'Union Pacific Corporation',
 'siemens': 'Siemens',
 'dior': 'Dior',
 'ups': 'United Parcel Service',
 'morgan-stanley': 'Morgan Stanley',
 'conocophillips': 'ConocoPhillips',
 'caterpillar': 'Caterpillar',
 'sp-global': 'S&P Global',
 'general-electric': 'General Electric',
 'honeywell': 'Honeywell',
 'royal-bank-of-canada': 'Royal Bank Of Canada',
 'uber': 'Uber',
 'inditex': 'Inditex',
 'anheuser-busch-inbev': 'Anheuser-Busch Inbev',
 'applied-materials': 'Applied Materials',
 'american-express': 'American Express',
 'nextera-energy': 'Nextera Energy',
 'att': 'AT&T',
 'deutsche-telekom': 'Deutsche Telekom',
 'airbus': 'Airbus',
 'unilever': 'Unilever',
 'lowes-companies': "Lowe's Companies",
 'commonwealth-bank': 'Commonwealth Bank',
 'raytheon-technologies': 'Raytheon Technologies',
 'sanofi': 'Sanofi',
 'rio-tinto': 'Rio Tinto',
 'charles-schwab': 'Charles Schwab',
 'goldman-sachs': 'Goldman Sachs',
 'booking-holdings': 'Booking Holdings (Booking.com)',
 'elevance-health': 'Elevance Health',
 'lockheed-martin': 'Lockheed Martin',
 'blackrock': 'BlackRock',
 'prologis': 'Prologis',
 'stryker-corporation': 'Stryker Corporation',
 'starbucks': 'Starbucks',
 'intuitive-surgical': 'Intuitive Surgical',
 'sony': 'Sony',
 'nippon-telegraph-and-telephone': 'NTT (Nippon Telegraph & Telephone)',
 'mitsubishi-ufj-financial': 'Mitsubishi UFJ Financial',
 'toronto-dominion-bank': 'Toronto Dominion Bank',
 'medtronic': 'Medtronic',
 'schneider-electric': 'Schneider Electric',
 'deere-company': 'Deere & Company',
 'allianz': 'Allianz',
 'bristol-myers-squibb': 'Bristol-Myers Squibb',
 'tjx-companies': 'TJX Companies',
 'bp': 'BP',
 'keyence': 'Keyence',
 'catl': 'CATL',
 'air-liquide': 'Air Liquide',
 'mondelez': 'Mondelez',
 'american-tower': 'American Tower',
 'gilead-sciences': 'Gilead Sciences',
 'marsh-and-mclennan-companies': 'Marsh & McLennan Companies',
 'taqa': 'TAQA',
 'cvs-health': 'CVS Health',
 'petrobras': 'Petrobras',
 'automatic-data-processing': 'Automatic Data Processing',
 'progressive': 'Progressive',
 'cm-bank': 'CM Bank',
 'citigroup': 'Citigroup',
 'palo-alto-networks': 'Palo Alto Networks',
 'aia': 'AIA',
 'lam-research': 'Lam Research',
 'shopify': 'Shopify',
 'china-life-insurance': 'China Life Insurance',
 'analog-devices': 'Analog Devices',
 'ubs': 'UBS',
 'regeneron-pharmaceuticals': 'Regeneron Pharmaceuticals',
 'eaton': 'Eaton',
 'ping-an-insurance': 'Ping An Insurance',
 'chubb': 'Chubb',
 'vertex-pharmaceuticals': 'Vertex Pharmaceuticals',
 'equinor': 'Equinor',
 'essilor-luxottica': 'EssilorLuxottica',
 'airbnb': 'Airbnb',
 'kohlberg-kravis-roberts': 'KKR & Co.',
 'csl': 'CSL',
 'sinopec': 'Sinopec',
 'icici-bank': 'ICICI Bank',
 'zoetis': 'Zoetis',
 'micron-technology': 'Micron Technology',
 'blackstone-group': 'Blackstone Group',
 'porsche': 'Porsche',
 'al-rajhi-bank': 'Al Rajhi Bank',
 'synopsys': 'Synopsys',
 'china-shenhua-energy': 'China Shenhua Energy',
 'boston-scientific': 'Boston Scientific',
 'mercadolibre': 'MercadoLibre',
 'byd': 'BYD',
 'cnooc': 'CNOOC',
 'diageo': 'Diageo',
 'fiserv': 'Fiserv',
 'iberdrola': 'Iberdrola',
 'southern-company': 'Southern Company',
 'compagnie-financiere-richemont': 'Compagnie Financière Richemont',
 'wuliangye-yibin': 'Wuliangye Yibin',
 'china-yangtze-power': 'China Yangtze Power',
 'lg-energy-solution': 'LG Energy Solution',
 'canadian-national-railway': 'Canadian National Railway',
 'bnp-paribas': 'BNP Paribas',
 'cme-group': 'CME Group',
 'equinix': 'Equinix',
 'abb': 'ABB',
 'zurich-insurance-group': 'Zurich Insurance Group',
 'cigna': 'Cigna',
 'sherwin-williams': 'Sherwin-Williams',
 'fast-retailing': 'Fast Retailing',
 'glaxo-smith-kline': 'GlaxoSmithKline',
 'illinois-tool-works': 'Illinois Tool Works',
 'enbridge': 'Enbridge',
 'infosys': 'Infosys',
 'safran': 'Safran',
 'relx': 'RELX',
 'altria-group': 'Altria Group',
 'atlas-copco': 'Atlas Copco',
 'axa': 'AXA',
 'duke-energy': 'Duke Energy',
 'kla': 'KLA',
 'mercedes-benz-group': 'Mercedes-Benz',
 'northrop-grumman': 'Northrop Grumman',
 'enel': 'Enel',
 'workday': 'Workday',
 'vinci': 'Vinci',
 'tokyo-electron': 'Tokyo Electron',
 'bmw': 'BMW',
 'hindustan-unilever': 'Hindustan Unilever',
 'cadence-design-systems': 'Cadence Design Systems',
 'bharti-airtel': 'Bharti Airtel',
 'eog-resources': 'EOG Resources',
 'glencore': 'Glencore',
 'schlumberger': 'Schlumberger',
 'bank-central-asia': 'Bank Central Asia',
 'waste-management': 'Waste Management',
 'stellantis': 'Stellantis',
 'meituan-dianping': 'Meituan',
 'arista-networks': 'Arista Networks',
 'general-dynamics': 'General Dynamics',
 'sk-hynix': 'SK Hynix',
 'moodys': "Moody's",
 'canadian-pacific-railway': 'Canadian Pacific Railway',
 'hca-healthcare': 'HCA Healthcare',
 'netease': 'NetEase',
 'fedex': 'FedEx',
 'shin-etsu-chemical': 'Shin-Etsu Chemical',
 'becton-dickinson': 'Becton Dickinson',
 'itc': 'ITC',
 'santander': 'Santander',
 'canadian-natural-resources': 'Canadian Natural Resources',
 'merck-kgaa': 'Merck KGaA',
 'sumitomo-mitsui-financial-group': 'Sumitomo Mitsui Financial Group',
 'walmex': 'Walmex',
 'ferrari': 'Ferrari',
 'state-bank-of-india': 'State Bank of India',
 'volkswagen': 'Volkswagen',
 'adnoc-gas': 'ADNOC Gas',
 'kddi': 'KDDI',
 'csx-corporation': 'CSX Corporation',
 'arm-holdings': 'Arm Holdings',
 'british-american-tobacco': 'British American Tobacco',
 'rosneft': 'Rosneft',
 'siemens-healthineers': 'Siemens Healthineers',
 'nongfu-spring': 'Nongfu Spring',
 'aon': 'Aon',
 'intercontinental-exchange': 'Intercontinental Exchange',
 'mitsubishi-corporation': 'Mitsubishi Corporation',
 'thomson-reuters': 'Thomson Reuters',
 'investor-ab': 'Investor AB',
 'sabic': 'SABIC',
 'vale': 'Vale',
 'itau-unibanco': 'Itaú Unibanco',
 'paypal': 'PayPal',
 'colgate-palmolive': 'Colgate-Palmolive',
 'hitachi': 'Hitachi',
 'dassault-systemes': 'Dassault Systèmes',
 'sberbank': 'Sberbank',
 'bank-of-montreal': 'Bank of Montreal',
 'target': 'Target',
 'us-bancorp': 'U.S. Bancorp',
 'china-telecom': 'China Telecom',
 'snowflake': 'Snowflake',
 'london-stock-exchange': 'London Stock Exchange',
 'vmware': 'Vmware',
 'chugai-pharmaceutical': 'Chugai Pharmaceutical',
 'chipotle-mexican-grill': 'Chipotle Mexican Grill',
 'marriott-international': 'Marriott International',
 'dbs': 'DBS Group',
 'hdfc': 'Housing Development Finance Corporation',
 'mckesson': 'McKesson',
 'national-australia-bank': 'National Australia Bank',
 'lululemon-athletica': 'lululemon athletica',
 'oriental-land': 'Oriental Land',
 'humana': 'Humana',
 'deutsche-post': 'DHL Group (Deutsche Post)',
 'life-insurance-corporation-of-india': 'Life Insurance Corporation of India (LIC)',
 'air-products-and-chemicals': 'Air Products and Chemicals',
 'southern-copper': 'Southern Copper',
 'america-movil': 'America Movil',
 'crowdstrike': 'CrowdStrike',
 '3m': '3M',
 'postal-savings-bank-of-china': 'Postal Savings Bank of China',
 'softbank': 'SoftBank',
 'munich-re': 'Munich RE (Münchener Rück)',
 'itochu-shoji': 'Itōchū Shōji',
 'roper-technologies': 'Roper Technologies',
 'enterprise-products': 'Enterprise Products',
 'recruit': 'Recruit',
 'o-reilly-automotive': "O'Reilly Automotive",
 'monster-beverage': 'Monster Beverage',
 'cintas': 'Cintas',
 'parker-hannifin': 'Parker-Hannifin',
 'pnc-financial-services': 'PNC Financial Services',
 'brookfield-corporation': 'Brookfield Corporation',
 'larsen-and-toubro': 'Larsen & Toubro',
 'amphenol': 'Amphenol',
 'kering': 'Kering',
 'phillips-66': 'Phillips 66',
 'nxp-semiconductors': 'NXP Semiconductors',
 'the-saudi-national-bank': 'The Saudi National Bank',
 'nintendo': 'Nintendo',
 'ecolab': 'Ecolab',
 'alimentation-couche-tard': 'Alimentation Couche-Tard',
 'freeport-mcmoran': 'Freeport-McMoRan',
 'marathon-petroleum': 'Marathon Petroleum',
 'charter-communications': 'Charter Communications',
 'bajaj-finance': 'Bajaj Finance',
 'scotiabank': 'Scotiabank',
 'lukoil': 'Lukoil',
 'transdigm': 'TransDigm',
 'heineken': 'Heineken',
 'motorola-solutions': 'Motorola Solutions',
 'intesa-sanpaolo': 'Intesa Sanpaolo',
 'trane-technologies': 'Trane Technologies',
 'bbva': 'Banco Bilbao Vizcaya Argentaria',
 'daiichi-sankyo': 'Daiichi Sankyō',
 'mitsui-bussan': 'Mitsui Bussan',
 'eni': 'ENI',
 'fortescue': 'Fortescue',
 'bank-rakyat-indonesia': 'Bank Rakyat Indonesia',
 'infineon': 'Infineon',
 'arthur-gallagher': 'Arthur J. Gallagher & Co.',
 'apollo-global-management': 'Apollo Global Management',
 'pioneer-natural-resources': 'Pioneer Natural Resources',
 'bank-of-communications': 'Bank of Communications',
 'alpha-dhabi': 'Alpha Dhabi',
 'constellation-software': 'Constellation Software',
 'crown-castle': 'Crown Castle',
 'tokio-marine': 'Tokio Marine',
 'emerson': 'Emerson',
 'saudi-telecom-company': 'Saudi Telecom Company',
 'westpac-banking': 'Westpac Banking',
 'republic-services': 'Republic Services',
 'norfolk-southern': 'Norfolk Southern',
 'novatek': 'Novatek',
 'mindray': 'Mindray',
 'paccar': 'Paccar',
 'occidental-petroleum': 'Occidental Petroleum',
 'national-grid': 'National Grid',
 'ing': 'ING',
 'midea': 'Midea',
 'honda': 'Honda',
 'simon-property': 'Simon Property Group',
 'universal-music-group': 'Universal Music Group',
 'dell': 'Dell',
 'reckitt-benckiser': 'Reckitt Benckiser',
 'volvo': 'Volvo Group',
 'anz-bank': 'ANZ Bank',
 'atlassian': 'Atlassian',
 'estee-lauder': 'Estee Lauder',
 'public-storage': 'Public Storage',
 'welltower': 'Welltower',
 'aflac': 'Aflac',
 'autodesk': 'Autodesk',
 'mediatek': 'MediaTek',
 'unicredit': 'UniCredit',
 'xiaomi': 'Xiaomi',
 'carrier': 'Carrier',
 'metlife': 'MetLife',
 'banco-santander-brasil': 'Banco Santander Brasil',
 'microchip-technology': 'Microchip Technology',
 'general-motors': 'General Motors',
 'japan-tobacco': 'Japan Tobacco',
 'aig': 'American International Group',
 'sempra-energy': 'Sempra Energy',
 'fomento-economico-mexicano': 'Fomento Económico Mexicano',
 'dr-horton': 'D. R. Horton',
 'truist-financial': 'Truist Financial',
 'crh': 'Cement Roadstone Holding',
 'autozone': 'AutoZone',
 'copart': 'Copart',
 'newmont': 'Newmont',
 'ambev': 'Ambev',
 'sika': 'Sika',
 'marvell': 'Marvell Technology Group',
 'paychex': 'Paychex',
 'keurig-dr-pepper': 'Keurig Dr Pepper',
 'foxconn': 'Foxconn (Hon Hai Precision Industry)',
 'energy-transfer-partners': 'Energy Transfer Partners',
 'kraft-heinz': 'Kraft Heinz',
 'compass-group': 'Compass Group',
 'denso': 'Denso',
 'hcl-technologies': 'HCL Technologies',
 'emirates-telecom-etisalat-group': 'Emirates Telecom (Etisalat Group)',
 'capital-one': 'Capital One',
 'ross-stores': 'Ross Stores',
 'pacific-gas-and-electric': 'Pacific Gas and Electric',
 'takeda-pharmaceutical': 'Takeda Pharmaceutical',
 'hilton-hotels': 'Hilton Worldwide',
 'kotak-mahindra-bank': 'Kotak Mahindra Bank',
 'mizuho-financial-group': 'Mizuho Financial Group',
 'foxconn-industrial-internet': 'Foxconn Industrial Internet',
 'pernod-ricard': 'Pernod Ricard',
 'ford': 'Ford',
 'basf': 'BASF',
 'idexx-laboratories': 'IDEXX Laboratories',
 'stmicroelectronics': 'STMicroelectronics',
 'constellation-brands': 'Constellation Brands',
 'macquarie': 'Macquarie',
 'williams-companies': 'Williams Companies',
 'lafargeholcim': 'Holcim Group',
 'daikin': 'Daikin',
 'engie': 'ENGIE',
 'hikvision': 'Hikvision',
 'ocbc-bank': 'OCBC Bank',
 'square': 'Block',
 'zijin-mining': 'Zijin Mining',
 'jingdong-mall': 'Jingdong Mall',
 'valero': 'Valero Energy',
 'axis-bank': 'Axis Bank',
 'gazprom': 'Gazprom',
 'cheniere-energy': 'Cheniere Energy',
 'american-electric-power': 'American Electric Power',
 'digital-realty': 'Digital Realty',
 'the-travelers-companies': 'The Travelers Companies',
 'edwards-lifesciences': 'Edwards Lifesciences',
 'credit-agricole': 'Crédit Agricole',
 'te-connectivity': 'TE Connectivity',
 'seattle-genetics': 'Seagen',
 'old-dominion-freight-line': 'Old Dominion Freight Line',
 'danone': 'Danone',
 'bae-systems': 'BAE Systems',
 'bayan-resources': 'Bayan Resources',
 'industrial-bank': 'Industrial Bank',
 'citic-securities': 'CITIC Securities',
 'nordea-bank': 'Nordea Bank',
 'hess': 'Hess',
 'kimberly-clark': 'Kimberly-Clark',
 'jiangsu-hengrui-medicine': 'Jiangsu Hengrui Medicine',
 'hoya': 'Hoya',
 'hong-kong-exchanges-and-clearing': 'Hong Kong Exchanges & Clearing',
 'nucor': 'Nucor',
 'wesfarmers': 'Wesfarmers',
 'adyen': 'Adyen',
 'ww-grainger': 'W. W. Grainger',
 'cencora': 'Cencora',
 'msci': 'MSCI',
 'maruti-suzuki-india': 'Maruti Suzuki India',
 'kenvue': 'Kenvue',
 'qnb-qatar-national-bank': 'QNB (Qatar National Bank)',
 'cibc': 'CIBC',
 'first-abu-dhabi-bank': 'First Abu Dhabi Bank',
 'doordash': 'DoorDash',
 'baidu': 'Baidu',
 'archer-daniels-midland': 'Archer Daniels Midland (ADM)',
 'oneok': 'Oneok',
 'suncor-energy': 'Suncor Energy',
 'dominion-energy': 'Dominion Energy',
 'centene': 'Centene',
 'tc-energy': 'TC Energy',
 'realty-income': 'Realty Income',
 'fortinet': 'Fortinet',
 'iqvia': 'IQVIA',
 'maybank': 'Maybank',
 'kinder-morgan': 'Kinder Morgan',
 'luzhou-laojiao': 'Luzhou Laojiao',
 'exelon-corporation': 'Exelon Corporation',
 'nu-holdings': 'Nu Holdings',
 'titan-company': 'Titan Company',
 'lennar': 'Lennar',
 'adani-enterprises': 'Adani Enterprises',
 'samsung-biologics': 'Samsung Biologics',
 'johnson-controls': 'Johnson Controls',
 'general-mills': 'General Mills',
 'maaden': 'Maaden',
 'spotify': 'Spotify',
 'hershey-company': 'The Hershey Company',
 'palantir': 'Palantir',
 'haleon': 'Haleon',
 'woodside-energy': 'Woodside Energy',
 'agilent-technologies': 'Agilent Technologies',
 'sysco': 'Sysco',
 'bny-mellon': 'Bank of New York Mellon',
 'adidas': 'Adidas',
 'japan-post-bank': 'Japan Post Bank',
 'l3harris-technologies': 'L3Harris Technologies',
 'asian-paints': 'Asian Paints',
 'datadog': 'Datadog',
 'bce': 'BCE',
 'lloyds-banking-group': 'Lloyds Banking Group',
 'murata-seisakusho': 'Murata Manufacturing (Murata Seisakusho)',
 'grupo-mexico': 'Grupo México',
 'electronic-arts': 'Electronic Arts',
 'allstate': 'Allstate',
 'manulife-financial': 'Manulife Financial',
 'ferguson': 'Ferguson',
 'ametek': 'Ametek',
 'prudential-financial': 'Prudential Financial',
 'dow': 'Dow',
 'mplx': 'MPLX',
 'ameriprise-financial': 'Ameriprise Financial',
 'kuhne-nagel': 'Kühne + Nagel',
 'otis-worldwide': 'Otis Worldwide',
 'givaudan': 'Givaudan',
 'waste-connections': 'Waste Connections',
 'fastenal': 'Fastenal',
 'sun-pharmaceutical': 'Sun Pharmaceutical',
 'deutsche-boerse': 'Deutsche Börse',
 'constellation-energy': 'Constellation Energy',
 'alcon': 'Alcon',
 'uniper': 'Uniper',
 'li-auto': 'Li Auto',
 'gartner': 'Gartner',
 'cognizant-technology-solutions': 'Cognizant Technology Solutions',
 'experian': 'Experian',
 'e-on': 'E.ON',
 '7-eleven': '7-Eleven',
 'yum': 'Yum! Brands',
 'fidelity-national-information-services': 'Fidelity National Information Services',
 'partners-group': 'Partners Group',
 'interactive-brokers': 'Interactive Brokers',
 'capgemini': 'Capgemini',
 'biogen': 'Biogen',
 'uob': 'UOB',
 'ppg-industries': 'PPG Industries',
 'bank-mandiri': 'Bank Mandiri',
 'btg-pactual': 'BTG Pactual',
 'exor': 'Exor',
 'las-vegas-sands': 'Las Vegas Sands',
 'the-trade-desk': 'The Trade Desk',
 'compagnie-de-saint-gobain': 'Compagnie de Saint-Gobain',
 'coinbase': 'Coinbase',
 'costar-group': 'CoStar Group',
 'wolters-kluwer': 'Wolters Kluwer',
 'xcel-energy': 'Xcel Energy',
 'bayer': 'Bayer',
 'verisk-analytics': 'Verisk Analytics',
 'anglo-american': 'Anglo American',
 'ares-management': 'Ares Management',
 'united-rentals': 'United Rentals',
 'wanhua-chemical': 'Wanhua Chemical',
 'naspers': 'Naspers',
 'kuwait-finance-house': 'Kuwait Finance House',
 'ntpc-limited': 'NTPC Limited',
 'dsv': 'DSV',
 'on-semiconductor': 'ON Semiconductor',
 'hyundai': 'Hyundai',
 'verbund': 'Verbund AG',
 'cummins': 'Cummins',
 'mobileye': 'Mobileye',
 'rwe': 'RWE',
 'bajaj-finserv': 'Bajaj Finserv',
 'swiss-re': 'Swiss Re',
 'baker-hughes': 'Baker Hughes',
 'ultratech-cement': 'UltraTech Cement',
 'beiersdorf': 'Beiersdorf',
 'kroger': 'Kroger',
 'rbi': 'Restaurant Brands International',
 'rockwell-automation': 'Rockwell Automation',
 'citic-bank': 'CITIC Bank',
 'east-money': 'East Money Information',
 'orange': 'Orange',
 'dmart': 'DMart',
 'consolidated-edison': 'Consolidated Edison',
 'generali': 'Generali',
 'corteva': 'Corteva',
 'vici-properties': 'VICI Properties',
 'banco-do-brasil': 'Banco do Brasil',
 'smc': 'SMC corp',
 'tata-motors': 'Tata Motors',
 'halliburton': 'Halliburton',
 'nasdaq': 'Nasdaq',
 'global-payments': 'Global Payments',
 'amadeus-it-group': 'Amadeus IT Group',
 'caixabank': 'CaixaBank',
 'wuxi-apptec': 'WuXi AppTec',
 'thales': 'Thales',
 'moderna': 'Moderna',
 'prudential': 'Prudential',
 'pseg': 'PSEG',
 'rolls-royce-holdings': 'Rolls-Royce Holdings',
 'luxshare-precision': 'Luxshare Precision',
 'ge-healthcare-technologies': 'GE HealthCare Technologies',
 'henkel': 'Henkel',
 'royal-caribbean': 'Royal Caribbean',
 'dupont-de-nemours': 'Dupont De Nemours',
 'muyuan-foods': 'Muyuan Foods',
 'lyondellbasell': 'LyondellBasell',
 'cenovus-energy': 'Cenovus Energy',
 'imperial-oil': 'Imperial Oil',
 'extra-space-storage': 'Extra Space Storage',
 'smic': 'SMIC',
 'swisscom': 'Swisscom',
 'weg-on': 'WEG ON',
 'sun-life-financial': 'Sun Life Financial',
 'great-west-lifeco': 'Great-West Lifeco',
 'kuaishou-technology': 'Kuaishou Technology',
 'barrick-gold': 'Barrick Gold',
 'zscaler': 'Zscaler',

In [15]:
# Thay lại tên các công ty
data_frames = [marketcap_df, revenue_df, earnings_df, eps_df, debts_df, net_assets_df, total_assets_df, cash_on_hand_df]
for df in data_frames:
    df['Company'].replace(companies_dict, inplace=True)

In [16]:
# Đổi lại tên cột
companies_df = companies_df.rename(columns={'Name': 'Company',})
eps_df = eps_df.rename(columns={'2023 (TTM)': '2023',})
earnings_df = earnings_df.rename(columns={'2023 (TTM)': '2023',})
revenue_df = revenue_df.rename(columns={'2023 (TTM)': '2023',})

In [18]:
companies_df.tail(5)

,Company,Country,Share price,Categories
1995,Taishin Financial Holdings,Taiwan,$0.57,"🏦 Banks, 💳 Financial services"
1996,SAAB AB,Sweden,$52.39,"🚀 Aerospace, 🔫 Defense contractors"
1997,Carvana,USA,$40.26,"🛒 E-Commerce, 🖥️ Internet, 🚘 Used car retailer..."
1998,KBR,USA,$52.24,👷 Engineering
1999,VF Corporation,USA,$18.14,"👚 Clothing, 👟 Footwear"

In [19]:
assert (marketcap_df['Company'].tail(5).tolist() == ['Taishin Financial Holdings', 'SAAB AB', 'Carvana', 'KBR', 'VF Corporation'])
assert (revenue_df['Company'].tail(5).tolist() == ['Taishin Financial Holdings', 'SAAB AB', 'Carvana', 'KBR', 'VF Corporation'])
assert (earnings_df['Company'].tail(5).tolist() == ['Taishin Financial Holdings', 'SAAB AB', 'Carvana', 'KBR', 'VF Corporation'])
assert (eps_df['Company'].tail(5).tolist() == ['Taishin Financial Holdings', 'SAAB AB', 'Carvana', 'KBR', 'VF Corporation'])
assert (debts_df['Company'].tail(5).tolist() == ['Taishin Financial Holdings', 'SAAB AB', 'Carvana', 'KBR', 'VF Corporation'])
assert (net_assets_df['Company'].tail(5).tolist() == ['Taishin Financial Holdings', 'SAAB AB', 'Carvana', 'KBR', 'VF Corporation'])
assert (total_assets_df['Company'].tail(5).tolist() == ['Taishin Financial Holdings', 'SAAB AB', 'Carvana', 'KBR', 'VF Corporation'])
assert (cash_on_hand_df['Company'].tail(5).tolist() == ['Taishin Financial Holdings', 'SAAB AB', 'Carvana', 'KBR', 'VF Corporation'])

Ta sẽ merge các DataFrame nhỏ thành một DataFrame lớn, với các cột là:

- `Company`

- `Year`

- `EPS`

- `Earnings`

- `Revenue`

- `Marketcap`

- `Total Debts`

- `Net Assets`

- `Total Assets`

- `Cash on hand`

- `Country`

- `Categories`

Để làm được điều đó, trước tiên ta phải `melt` các `dataframe` hiện có

In [21]:
eps_melted_df = eps_df.melt(id_vars='Company', var_name='Year', value_name='EPS')
earnings_melted_df = earnings_df.melt(id_vars='Company', var_name='Year', value_name='Earnings')
revenue_melted_df = revenue_df.melt(id_vars='Company', var_name='Year', value_name='Revenue')
marketcap_melted_df = marketcap_df.melt(id_vars='Company', var_name='Year', value_name='Marketcap')

debts_melted_df = debts_df.melt(id_vars='Company', var_name='Year', value_name='Total Debts')
net_assets_melted_df = net_assets_df.melt(id_vars='Company', var_name='Year', value_name='Net Assets')
total_assets_melted_df = total_assets_df.melt(id_vars='Company', var_name='Year', value_name='Total Assets')
cash_on_hand_melted_df = cash_on_hand_df.melt(id_vars='Company', var_name='Year', value_name='Cash on hand')

In [22]:
cash_on_hand_melted_df.head(10)

                     Company  Year Cash on hand
0                      Apple  2023     $61.55 B
1                  Microsoft  2023    $111.26 B
2               Saudi Aramco  2023          NaN
3          Alphabet (Google)  2023          NaN
4                     Amazon  2023          NaN
5                     NVIDIA  2023     $13.29 B
6  Meta Platforms (Facebook)  2023          NaN
7         Berkshire Hathaway  2023          NaN
8                      Tesla  2023          NaN
9                  Eli Lilly  2023          NaN

In [23]:
# Merge các dataframe lại
merged_df = pd.merge(eps_melted_df, earnings_melted_df, on=['Company', 'Year'], how='outer')
merged_df = pd.merge(merged_df, revenue_melted_df, on=['Company', 'Year'], how='outer')
merged_df = pd.merge(merged_df, marketcap_melted_df, on=['Company', 'Year'], how='outer')

merged_df = pd.merge(merged_df, debts_melted_df, on=['Company', 'Year'], how='outer')
merged_df = pd.merge(merged_df, net_assets_melted_df, on=['Company', 'Year'], how='outer')
merged_df = pd.merge(merged_df, total_assets_melted_df, on=['Company', 'Year'], how='outer')
merged_df = pd.merge(merged_df, cash_on_hand_melted_df, on=['Company', 'Year'], how='outer')

merged_df = pd.merge(merged_df, companies_df,on=['Company'], how='outer' )
merged_df.sample(10)

,Company,Year,EPS,Earnings,Revenue,Marketcap,Total Debts,Net Assets,Total Assets,Cash on hand,Country,Share price,Categories
16908,Cheniere Energy,2009,-$3.17,-$0.17 B,$0.14 B,$0.13 B,$3.04 B,$-0.44 B,$2.73 B,$88.37 M,USA,$176.21,NaN
68813,Industrial Bank of Korea (IBK),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,South Korea,$9.03,"🏦 Banks, 💳 Financial services"
39810,Great Wall Motors,2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,China,$3.63,"🚗 Automakers, 🏭 Manufacturing"
31507,Givaudan,2007,$42.99,$0.41 B,$2.39 B,$6.84 B,$3.28 B,$2.37 B,$6.97 B,$0.45 B,Switzerland,"$3,875","Flavors & Fragrances, 💄 Cosmetics and Beauty"
5039,Bank Central Asia,2021,$0.01763,$2.68 B,$5.53 B,$62.99 B,$0.16 B,$14.19 B,$85.98 B,$13.17 B,Indonesia,$0.56,"🏦 Banks, 💳 Financial services"
15447,Cheniere Energy,2012,-$1.81,-$0.35 B,$0.26 B,$4.19 B,$2.16 B,$2.26 B,$4.63 B,$0.20 B,USA,$176.21,NaN
13039,Cheniere Energy,2017,-$1.70,$0.56 B,$5.60 B,$12.79 B,$25.33 B,$1.24 B,$27.90 B,$0.72 B,USA,$176.21,NaN
46167,Hormel Foods,2017,$1.60,$1.29 B,$9.16 B,$19.27 B,$0.25 B,$4.93 B,$6.97 B,$0.44 B,USA,$31.38,🍴 Food
45074,Pembina Pipeline,2006,$0.64,$91.76 M,$0.29 B,NaN,$0.54 B,$0.73 B,$1.43 B,$1.59 M,Canada,$33.45,"🛢 Oil&Gas, 🚚 Transportation, ⚡ Energy, 🛣️ Infr..."
12667,Cheniere Energy,2017,-$1.70,$0.56 B,$5.60 B,$12.79 B,$25.33 B,$1.24 B,$27.90 B,$0.72 B,USA,$176.21,NaN

In [24]:
merged_df['Year'].unique()

array(['2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016',
       '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008',
       '2007', '2006', '2005', '2004', '2003', '2002', '2001'],
      dtype=object)

In [28]:
# Lưu dữ liệu vào file csv
merged_df.to_csv('../Data/raw/raw_data.csv', index=False)